# Generated by Django 4.0.4 on 2022-05-19 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('emp_code', models.CharField(max_length=100, primary_key='True', serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_comment', models.CharField(max_length=500)),
                ('expense_done_on', models.DateField(verbose_name='Date of Expenses :')),
                ('expense_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('vend_code', models.CharField(max_length=100, primary_key='True', serialize=False)),
            ],
        ),
    ]
