# Generated by Django 4.0.4 on 2022-05-20 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager', '0002_employee_expenses_expenses_expense_details_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='expenses',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='employee_expenses',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_manager.employee'),
        ),
    ]
