# Generated by Django 4.0.4 on 2022-05-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager', '0003_alter_employee_expenses_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='employee_expenses',
        ),
        migrations.AddField(
            model_name='vendor',
            name='employee_expenses',
            field=models.ManyToManyField(to='expense_manager.employee'),
        ),
    ]
