# Generated by Django 4.0.4 on 2022-05-20 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager', '0005_remove_employee_expenses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='emp_code',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='expense_manager.employee'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='vend_code',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='expense_manager.vendor'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='chair',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='desk',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='emp_code',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='expense_manager.employee'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='laptop',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='vendor',
            name='wifi',
            field=models.TextField(default=0),
        ),
    ]
