# Generated by Django 4.0.4 on 2022-05-20 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expense_manager', '0007_remove_vendor_chair_remove_vendor_desk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='emp_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_manager.employee'),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='vend_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_manager.vendor'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='emp_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expense_manager.employee'),
        ),
    ]
